name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: rubymthompson
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.rmthompson@willamette.edu }}
        password: ${{ secrets.Rubytillamook2020! }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.rubymthompson }}/jrembold/web2db:latest
